services:
  soketi:
    image: quay.io/soketi/soketi:latest
    container_name: soketi
    restart: unless-stopped
    environment:
      - SOKETI_SERVER_PORT=6001
      - SOKETI_DEFAULT_APP_ID=${SOKETI_DEFAULT_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${SOKETI_DEFAULT_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${SOKETI_DEFAULT_APP_SECRET}
      - SOKETI_APP_CLUSTER=${SOKETI_APP_CLUSTER}
      - SOKETI_DEBUG=${SOKETI_DEBUG}
      - SOKETI_METRICS_ENABLED=${SOKETI_METRICS_ENABLED}
    ports:
      - 6001:6001
      - 9601:9601
    command: ["soketi", "start"]

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN=ws.mijnepay.nl
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
  caddy_config:
